name: Publish

on:
  push:
    tags:
      - v*.*.* # only trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run tests
        # Only publish to PyPI if tests pass.
        run: pytest

      - name: Build and upload dist
        run: |
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*.tar.gz
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
