name: Tests

on:
  push:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/test.yml']
  pull_request:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/test.yml']

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        # [test]: see options.extras_require in setup.cfg
        run: pip install .[test]

      - name: Run tests
        run: pytest --durations 0 --cov
        env:
          ILOVEPDF_PUBLIC_KEY: ${{ secrets.ILOVEPDF_PUBLIC_KEY }}
