name: Tests

on:
  push:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/test.yml']
  pull_request:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/test.yml']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        # [test]: see options.extras_require in setup.cfg
        run: pip install .[test]

      - name: Run tests
        run: pytest --durations 0
        env:
          ILOVEPDF_PUBLIC_KEY: ${{ secrets.ILOVEPDF_PUBLIC_KEY }}
